name: Truncate Workflow History Pipeline

permissions:
  actions: write
  id-token: write
  contents: read
on:
  # Run daily, at 01:00.
  schedule:
    - cron: "0 1 * * *"

jobs:
  delete_past_runs:
    name: "Truncate github workflow run history"
    timeout-minutes: 15
    runs-on: ubuntu-latest
    steps:
      - name: "Delete workflow runs"
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: "${{ github.token }}"
          repository: "${{ github.repository }}"
          retain_days: 5
          keep_minimum_runs: 5

  slack-notifications:
    needs:
      - delete_past_runs
    if: always()
    uses: ./.github/workflows/slack-notifications.yaml
    with:
      env: dev
    secrets: inherit
